EXPLAIN
SELECT e.nom, COUNT(i.id)
FROM ETUDIANT e
JOIN INSCRIPTION i ON i.etudiant_id = e.id
GROUP BY e.id;

ALTER TABLE INSCRIPTION
ADD INDEX idx_date_inscr(date_inscription);

EXPLAIN
SELECT e.nom, COUNT(i.id)
FROM ETUDIANT e
JOIN INSCRIPTION i ON i.etudiant_id = e.id
GROUP BY e.id;

ALTER TABLE INSCRIPTION
DROP INDEX idx_date_inscr;

ANALYZE TABLE INSCRIPTION;
OPTIMIZE TABLE INSCRIPTION;
